.TH IP-Calculator 1
.SH NAME
IP-Calculator \- Calculates subnets and prints information about an IP address.
.SH SYNOPSIS
.B ip-calculator
[\fI\,OPTION\/\fR] <\fI\,IP ADDRESS\/\fR> [\fI\,NETMASK\/\fR]
.SH DESCRIPTION
The IP Calculator offers a comprehensive solution for subnetting and obtaining information about IP addresses. With its capability to divide a large network into smaller subnets, it makes managing and organizing your network simple. The calculator also has a feature that can quickly identify whether an IP address is classful or classless, providing a clear picture of your network's structure. In addition to calculating the number of subnets and host addresses per subnet, it can also create custom subnet masks. The Command Line Interface (CLI) enables easy input of IP addresses and provides concise and easily understandable outputs.
.SH OPTIONS
.TP
\fB\-s\fR <\fIamount of required subnets\fR>, \fB\-\-subnets\fR <\fIamount of required subnets\fR>
Devide the network into equal size subnetworks.
.TP
\fB\-e\fR <\fIamount of required hosts\fR>, \fB\-\-hosts\fR <\fIamount of required hosts\fR>
Devide the network into equal size subnetworks considering the required hosts.
.TP
\fB\-d\fR <\fIamount of required subnets\fR>..., \fB\-\-deviding\fR <\fIamount of required subnets\fR>...
Devide the network into subnetworks, then do it and stop when it runs out of requests.
.TP
\fB\-c\fR <\fIrequired hosts in cronological order\fR>..., \fB\-\-cronology\fR <\fIrequired hosts in cronological order\fR>...
Devides the network into subnetwork considering the required hosts and the order or requests.
.TP
\fB\-h\fR, \fB\-\-help\fR
Display the help page
.TP
\fB\-v\fR, \fB\-\-version\fR
Display the version
.SH EXAMPLES
.B ip-calculator
169.254.0.0
.br
.B ip-calculator
192.168.1.0
255.255.255.0
.br
.B ip-calculator
\fI\-s\fR
3
192.168.1.0
255.255.255.0
.br
.B ip-calculator
\fI\-e\fR
62
172.30.0.0
255.255.0.0
.br
.B ip-calculator
\fI\-d\fR
4[2] 2 3[1] 4
10.0.0.0
255.0.0.0
.br
.B ip-calculator
\fI\-c\fR
100 2000 50 30 200
92.128.0.0
255.128.0.0
.br
.B ip-calculator
\fI\-h\fR
.br
.B ip-calculator
\fI\-v\fR
.SH REPORTING BUGS
You can report bugs on the project's github page.
.br
<https://github.com/GamerFandor/IP-Calculator/issues>
.SH LICENCE
IP-Calculator Copyright (C) 2022 Andor Zoltán Fülöp
.br
This program comes with ABSOLUTELY NO WARRANTY; for details visit <https://gnu.org/licenses/gpl.html>.
.br
This is free software, and you are welcome to redistribute it
.br
under certain conditions; visit <https://gnu.org/licenses/gpl.html> for details.
.SH AUTHOR
Written by Andor Zoltán Fülöp. 